databases:
  - name: mepecoop-web-db
    databaseName: mepecoop_web
    user: mepecoop_user

services:
  - type: web
    name: mepe-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:      - key: DATABASE_URL
        fromDatabase:
          name: mepecoop-web-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "mepe.onrender.com"