# Generated by Django 5.2.1 on 2025-06-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebFarsl',
            fields=[
                ('fid', models.SmallIntegerField(db_column='fID', primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='fName', max_length=99, null=True)),
            ],
            options={
                'verbose_name': 'Web FARSL',
                'verbose_name_plural': 'Web FARSLs',
                'db_table': 'web_farsl',
            },
        ),
        migrations.CreateModel(
            name='WebMcust',
            fields=[
                ('fid', models.PositiveIntegerField(db_column='fID', primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='fName', max_length=90, null=True)),
                ('fpassword', models.CharField(blank=True, db_column='fPassword', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Web Customer',
                'verbose_name_plural': 'Web Customers',
                'db_table': 'web_mcust',
            },
        ),
        migrations.CreateModel(
            name='WebPcust',
            fields=[
                ('fauto', models.AutoField(db_column='fAUTO', primary_key=True, serialize=False)),
                ('fdoc', models.CharField(blank=True, db_column='fDoc', max_length=12, null=True)),
                ('fsdate', models.CharField(blank=True, db_column='fsDate', max_length=10, null=True)),
                ('frem', models.CharField(blank=True, db_column='fRem', max_length=45, null=True)),
                ('fsdr', models.CharField(blank=True, db_column='fsDr', max_length=18, null=True)),
                ('fscr', models.CharField(blank=True, db_column='fsCr', max_length=18, null=True)),
                ('fsbal', models.CharField(blank=True, db_column='fsBal', max_length=18, null=True)),
                ('fcust', models.ForeignKey(blank=True, db_column='fCUST', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.webmcust')),
                ('fsl', models.ForeignKey(blank=True, db_column='fSL', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.webfarsl')),
            ],
            options={
                'db_table': 'web_pcust',
            },
        ),
    ]
