# Generated by Django 5.2.1 on 2025-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebFarsl',
            fields=[
                ('fid', models.SmallIntegerField(db_column='fID', primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='fName', max_length=99, null=True)),
            ],
            options={
                'db_table': 'web_farsl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebMcust',
            fields=[
                ('fid', models.PositiveIntegerField(db_column='fID', primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='fName', max_length=90, null=True)),
                ('fpassword', models.CharField(blank=True, db_column='fPassword', max_length=45, null=True)),
            ],
            options={
                'db_table': 'web_mcust',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebPcust',
            fields=[
                ('fauto', models.AutoField(db_column='fAUTO', primary_key=True, serialize=False)),
                ('fcust', models.PositiveIntegerField(db_column='fCUST')),
                ('fsl', models.SmallIntegerField(blank=True, db_column='fSL', null=True)),
                ('fdoc', models.CharField(blank=True, db_column='fDoc', max_length=12, null=True)),
                ('fsdate', models.CharField(blank=True, db_column='fsDate', max_length=10, null=True)),
                ('frem', models.CharField(blank=True, db_column='fRem', max_length=45, null=True)),
                ('fsdr', models.CharField(blank=True, db_column='fsDr', max_length=18, null=True)),
                ('fscr', models.CharField(blank=True, db_column='fsCr', max_length=18, null=True)),
                ('fsbal', models.CharField(blank=True, db_column='fsBal', max_length=18, null=True)),
            ],
            options={
                'db_table': 'web_pcust',
                'managed': False,
            },
        ),
    ]
