# Generated by Django 5.2.1 on 2025-05-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webfarsl',
            options={},
        ),
        migrations.AlterModelOptions(
            name='webmcust',
            options={},
        ),
        migrations.AlterModelOptions(
            name='webpcust',
            options={},
        ),
    ]
